#!/bin/bash  

cat /dev/null > /var/log/syslog
cat /dev/null > /var/log/wtmp 
cat /dev/null > /var/log/maillog
cat /dev/null > /var/log/messages
cat /dev/null > /var/log/openwebmail.log
cat /dev/null > /var/log/maillog
cat /dev/null > /var/log/secure

sleep 1

killall -9 LoginServer

killall -9 GatewayServer

killall -9 TicketServer

killall -9 MissionServer

killall -9 WorldServer

killall -9 ZoneServer

sleep 1

find . -name "*.log.*" -type f -print -exec rm -rf {} \;

sleep 1

cd /root/PServerEE/TicketServer/
./TicketServer -p 2067 &
sleep 5
cd /root/PServerEE/GatewayServer/
./GatewayServer &
sleep 5
cd /root/PServerEE/LoginServer/
./LoginServer &
sleep 5
cd /root/PServerEE/MissionServer/
./MissionServer &
sleep 5
cd /root/PServerEE/WorldServer/
./WorldServer &
sleep 5
cd /root/PServerEE/ZoneServer/
./ZoneServer &
